# Datos del glosario ilustrado de Rosina.
# "simbolo" es el cuerpo de un SVG de 60x60 (trazo rosa); "icono" es un emoji para materiales.

S = 'stroke="#E74E96" stroke-width="3.2" stroke-linecap="round" stroke-linejoin="round" fill="none"'
G = 'stroke="#C9C9CF" stroke-width="3.2" stroke-linecap="round" fill="none"'
L = 'stroke="#9EA2F9" stroke-width="3.2" stroke-linecap="round" fill="none"'

def x(cx, cy, r=6, attrs=S):
    return f'<path d="M{cx-r},{cy-r} L{cx+r},{cy+r} M{cx+r},{cy-r} L{cx-r},{cy+r}" {attrs}/>'

CATEGORIAS = [
    ('basicos', 'Puntos básicos'),
    ('amigurumi', 'Técnicas de amigurumi'),
    ('tejido', 'Partes del tejido y patrones'),
    ('materiales', 'Materiales'),
]

TERMINOS = [
    # ---------- Puntos básicos ----------
    dict(id='cadeneta', cat='basicos', nombre='Cadeneta', abrev='cad', en='chain (ch)',
         simbolo=f'<ellipse cx="30" cy="30" rx="15" ry="8" {S}/>',
         definicion='Es el punto más sencillo y el comienzo de casi todo. Una fila de cadenetas forma la base de un tejido plano, y también se usa para subir de altura al inicio de una fila o para crear espacios.',
         pasos=['Haz un nudo corredizo y colócalo en la aguja.', 'Haz una lazada.', 'Pasa la lazada por el lazo que tienes en la aguja. ¡Ya tienes una cadeneta!'],
         tip='No aprietes demasiado las cadenetas de base: si quedan muy tensas, luego cuesta meter la aguja en ellas.'),
    dict(id='punto-deslizado', cat='basicos', nombre='Punto deslizado', abrev='pd', en='slip stitch (sl st)', otros='También se llama punto raso.',
         simbolo='<circle cx="30" cy="30" r="7" fill="#E74E96"/>',
         definicion='Es un punto sin altura. Sirve para unir el final de una vuelta con el principio, para desplazarte por el tejido sin que crezca, o para hacer un borde fino.',
         pasos=['Mete la aguja en el punto.', 'Haz una lazada.', 'Sácala de una vez por el punto y por el lazo de la aguja.']),
    dict(id='punto-bajo', cat='basicos', nombre='Punto bajo', abrev='pb', en='single crochet (sc) en EE. UU. / double crochet (dc) en Reino Unido',
         simbolo=x(30, 30, 11),
         definicion='El punto estrella del amigurumi: es bajito, firme y cerrado, así que el relleno no se ve. Casi todos los muñecos se tejen completos en punto bajo.',
         pasos=['Mete la aguja en el punto.', 'Haz una lazada y sácala: quedan 2 lazos en la aguja.', 'Haz otra lazada y pásala por los 2 lazos.'],
         tip='En el símbolo de los patrones el punto bajo puede aparecer como una X o como una cruz +. Significan lo mismo.'),
    dict(id='medio-punto-alto', cat='basicos', nombre='Medio punto alto', abrev='mpa', en='half double crochet (hdc) en EE. UU. / half treble (htr) en Reino Unido',
         simbolo=f'<path d="M30,14 V48 M18,14 H42" {S}/>',
         definicion='Un punto intermedio entre el punto bajo y el punto alto. Teje rápido y da un tejido suave; se usa mucho en gorros, mantas y bolsos.',
         pasos=['Haz una lazada antes de meter la aguja.', 'Mete la aguja en el punto, haz una lazada y sácala: quedan 3 lazos.', 'Haz una lazada y pásala por los 3 lazos a la vez.']),
    dict(id='punto-alto', cat='basicos', nombre='Punto alto', abrev='pa', en='double crochet (dc) en EE. UU. / treble (tr) en Reino Unido',
         simbolo=f'<path d="M30,12 V50 M18,12 H42 M23,35 L37,27" {S}/>',
         definicion='Un punto alto y calado, que hace crecer el tejido rápido. Es la base de muchos patrones de mantas, chales y el famoso cuadrado de la abuela (granny).',
         pasos=['Haz una lazada y mete la aguja en el punto.', 'Haz una lazada y sácala: quedan 3 lazos.', 'Lazada y pasa por 2 lazos.', 'Lazada y pasa por los 2 últimos.'],
         tip='Cada rayita diagonal en el símbolo es una lazada extra antes de meter la aguja: el punto alto tiene una, el punto alto doble tiene dos.'),
    dict(id='punto-alto-doble', cat='basicos', nombre='Punto alto doble', abrev='pad', en='treble (tr) en EE. UU. / double treble (dtr) en Reino Unido',
         simbolo=f'<path d="M30,10 V52 M18,10 H42 M23,30 L37,22 M23,40 L37,32" {S}/>',
         definicion='Todavía más alto que el punto alto. Se usa en tejidos calados, flores y detalles decorativos.',
         pasos=['Haz 2 lazadas y mete la aguja en el punto.', 'Haz una lazada y sácala: quedan 4 lazos.', 'Lazada y pasa por 2 lazos. Repite 2 veces más hasta que quede 1 lazo.']),

    # ---------- Técnicas de amigurumi ----------
    dict(id='anillo-magico', cat='amigurumi', nombre='Anillo mágico', abrev='am', en='magic ring (MR)', otros='También se llama aro mágico o anillo ajustable.',
         simbolo=f'<circle cx="28" cy="30" r="13" {S}/><path d="M41,30 C48,32 50,40 46,48" {S}/>',
         definicion='La forma de empezar casi cualquier pieza redonda. En lugar de una cadena cerrada, tejes los primeros puntos dentro de un aro de hilo y luego tiras de la hebra para cerrarlo por completo: el centro queda sin huequito.',
         pasos=['Enrolla el hilo alrededor de tus dedos formando un aro.', 'Mete la aguja en el aro, saca el hilo y haz 1 cadeneta (no cuenta como punto).', 'Teje los puntos que pida el patrón dentro del aro, por ejemplo 6 pb.', 'Tira de la hebra corta para cerrar el aro.'],
         tip='Antes de cortar el hilo al final, asegura bien la hebra del anillo mágico cosiéndola por dentro: si se suelta, el centro se abre.'),
    dict(id='aumento', cat='amigurumi', nombre='Aumento', abrev='aum', en='increase (inc)',
         simbolo=f'<path d="M30,50 L19,24 M30,50 L41,24" {S}/>' + x(17, 16, 5) + x(43, 16, 5),
         definicion='Tejer 2 puntos en el mismo punto de la vuelta anterior. Así la pieza crece y se va abriendo, como la parte de arriba de una cabeza.',
         pasos=['Teje un punto bajo.', 'Teje otro punto bajo en ese mismo punto.'],
         tip='Si los aumentos caen siempre en el mismo sitio, la pieza queda hexagonal. Cámbialos de lugar en cada vuelta y usa la calculadora de Rosina para repartirlos.',
         enlace=('recursos-rosina.html#calculadora', 'Abrir la calculadora de aumentos')),
    dict(id='disminucion', cat='amigurumi', nombre='Disminución', abrev='dism', en='decrease (dec) / single crochet two together (sc2tog)',
         simbolo=f'<path d="M30,12 L19,38 M30,12 L41,38" {S}/>' + x(17, 46, 5) + x(43, 46, 5),
         definicion='Unir 2 puntos de la vuelta anterior en uno solo. La pieza se va cerrando, como la parte de abajo de una cabeza o el final de un brazo.',
         pasos=['Mete la aguja en el primer punto, haz una lazada y sácala.', 'Mete la aguja en el siguiente punto, haz una lazada y sácala: quedan 3 lazos.', 'Haz una lazada y pásala por los 3 lazos.']),
    dict(id='disminucion-invisible', cat='amigurumi', nombre='Disminución invisible', abrev='dism inv', en='invisible decrease (inv dec)',
         simbolo=f'<path d="M30,12 L19,34 M30,12 L41,34" {S}/>' + x(17, 42, 5) + x(43, 42, 5) + f'<path d="M11,52 Q17,56 23,52 M37,52 Q43,56 49,52" {S}/>',
         definicion='Una disminución que casi no se nota, ideal para amigurumis. Se teje solo por las hebras delanteras, así que no deja el bultico que deja la disminución normal.',
         pasos=['Mete la aguja solo en la hebra delantera del primer punto.', 'Sin sacar la aguja, métela también en la hebra delantera del siguiente punto.', 'Haz una lazada y sácala por esas 2 hebras: quedan 2 lazos.', 'Haz una lazada y pásala por los 2 lazos.'],
         tip='Es la disminución favorita para amigurumis: la cabeza y el cuerpo quedan lisos, sin huequitos.'),
    dict(id='espiral', cat='amigurumi', nombre='Tejer en espiral', abrev='', en='working in continuous rounds / in the round',
         simbolo=f'<path d="M31.2,30.0 L31.3,30.1 L31.3,30.2 L31.4,30.4 L31.4,30.5 L31.5,30.7 L31.5,30.8 L31.4,31.0 L31.4,31.2 L31.4,31.4 L31.3,31.5 L31.2,31.7 L31.1,31.9 L31.0,32.0 L30.8,32.2 L30.6,32.3 L30.4,32.4 L30.2,32.6 L30.0,32.6 L29.8,32.7 L29.5,32.8 L29.3,32.8 L29.0,32.8 L28.7,32.8 L28.4,32.7 L28.2,32.6 L27.9,32.5 L27.6,32.4 L27.4,32.2 L27.1,32.0 L26.9,31.8 L26.7,31.6 L26.5,31.3 L26.3,31.0 L26.1,30.7 L26.0,30.4 L25.9,30.0 L25.8,29.7 L25.8,29.3 L25.8,28.9 L25.8,28.5 L25.9,28.1 L26.0,27.7 L26.2,27.4 L26.4,27.0 L26.6,26.6 L26.8,26.3 L27.1,25.9 L27.4,25.6 L27.8,25.4 L28.2,25.1 L28.6,24.9 L29.0,24.7 L29.5,24.6 L30.0,24.5 L30.4,24.4 L30.9,24.4 L31.5,24.4 L32.0,24.5 L32.5,24.6 L33.0,24.8 L33.5,25.0 L33.9,25.2 L34.4,25.5 L34.8,25.9 L35.2,26.3 L35.6,26.7 L35.9,27.2 L36.2,27.7 L36.5,28.2 L36.7,28.7 L36.9,29.3 L37.0,29.9 L37.1,30.5 L37.1,31.2 L37.0,31.8 L36.9,32.4 L36.7,33.1 L36.5,33.7 L36.2,34.3 L35.9,34.8 L35.5,35.4 L35.1,35.9 L34.6,36.4 L34.1,36.8 L33.5,37.2 L32.9,37.6 L32.2,37.9 L31.5,38.1 L30.8,38.3 L30.1,38.4 L29.4,38.5 L28.6,38.5 L27.9,38.4 L27.1,38.3 L26.4,38.1 L25.6,37.8 L24.9,37.4 L24.3,37.0 L23.6,36.6 L23.0,36.0 L22.4,35.5 L21.9,34.8 L21.5,34.1 L21.1,33.4 L20.7,32.6 L20.4,31.8 L20.2,31.0 L20.1,30.1 L20.1,29.3 L20.1,28.4 L20.2,27.5 L20.4,26.7 L20.6,25.8 L20.9,25.0 L21.3,24.1 L21.8,23.4 L22.4,22.6 L23.0,21.9 L23.7,21.3 L24.4,20.7 L25.2,20.2 L26.1,19.7 L26.9,19.3 L27.9,19.0 L28.8,18.8 L29.8,18.7 L30.8,18.6 L31.8,18.6 L32.8,18.8 L33.8,19.0 L34.8,19.3 L35.7,19.7 L36.6,20.1 L37.5,20.7 L38.4,21.3 L39.1,22.0 L39.9,22.8 L40.5,23.6 L41.1,24.6 L41.6,25.5 L42.0,26.5 L42.4,27.6 L42.6,28.6 L42.8,29.7 L42.8,30.9 L42.8,32.0 L42.6,33.1 L42.4,34.2 L42.1,35.3 L41.6,36.4 L41.1,37.4 L40.5,38.4 L39.8,39.3 L39.0,40.2 L38.1,41.0 L37.1,41.8 L36.1,42.4 L35.0,43.0 L33.9,43.4 L32.8,43.8 L31.5,44.1 L30.3,44.2 L29.1,44.3 L27.8,44.2 L26.6,44.1 L25.3,43.8 L24.1,43.4 L22.9,42.9 L21.8,42.3 L20.7,41.6 L19.7,40.8 L18.7,39.9 L17.8,39.0 L17.0,37.9 L16.3,36.8 L15.7,35.6 L15.2,34.4 L14.8,33.1 L14.5,31.7 L14.3,30.4" {S}/><path d="M30,30" {S}/>',
         definicion='Tejer vuelta tras vuelta sin cerrar con punto deslizado, como un caracol. Es la forma más común de tejer amigurumis porque no deja costura.',
         pasos=['Coloca un marcador en el primer punto de la vuelta.', 'Teje la vuelta completa y sigue directo con la siguiente, sin cerrar.', 'Al llegar al marcador, muévelo al primer punto de la vuelta nueva.'],
         tip='Sin marcador en espiral es facilísimo perder la cuenta. Un clip o un trocito de hilo de otro color te salvan.'),
    dict(id='vuelta-cerrada', cat='amigurumi', nombre='Vuelta cerrada', abrev='', en='joined rounds',
         simbolo=''.join(x(30 + 16 * c, 30 + 16 * s, 3.2) for c, s in [(1, 0), (0.5, 0.87), (-0.5, 0.87), (-1, 0), (-0.5, -0.87)]) + '<circle cx="38" cy="16.1" r="4" fill="#E74E96"/>',
         definicion='Lo contrario de tejer en espiral: al final de cada vuelta la cierras con un punto deslizado en el primer punto y subes con cadenetas antes de empezar la siguiente. Se usa cuando cambias de color cada vuelta o en cuadrados y mandalas.',
         pasos=['Teje la vuelta completa.', 'Cierra con 1 pd en el primer punto de la vuelta.', 'Sube con las cadenetas que pida el patrón y empieza la vuelta siguiente.']),
    dict(id='cambio-de-color', cat='amigurumi', nombre='Cambio de color', abrev='', en='color change',
         simbolo=f'<path d="M19,19 L41,41" {S}/><path d="M41,19 L19,41" {L}/>',
         definicion='Cambiar de hilo sin que se note el salto. El truco está en hacer el último paso del punto anterior con el color nuevo.',
         pasos=['Teje el último punto del color viejo hasta que queden 2 lazos en la aguja.', 'Haz la lazada final con el color nuevo y pásala por los 2 lazos.', 'Sigue tejiendo con el color nuevo y anuda las hebras por dentro.']),
    dict(id='rematar', cat='amigurumi', nombre='Rematar y cerrar', abrev='', en='fasten off',
         simbolo=f'<path d="M30,10 V26" {S}/><circle cx="30" cy="34" r="8" {S}/><path d="M30,42 C30,50 40,50 44,54" {S}/>',
         definicion='Terminar una pieza para que no se desteja. En amigurumi, además, se cierra el hueco final para que no se vea el relleno.',
         pasos=['Corta el hilo dejando una hebra larga.', 'Pásala por el lazo de la aguja y tira para asegurar.', 'Para cerrar la pieza, pasa la hebra con la aguja lanera por la hebra delantera de los últimos puntos y tensa como una bolsita.', 'Esconde la hebra metiéndola por dentro del muñeco.']),
    dict(id='costura', cat='amigurumi', nombre='Coser piezas', abrev='', en='sewing / assembly',
         simbolo=f'<path d="M10,30 H50" {G}/><path d="M14,22 L20,38 M26,22 L32,38 M38,22 L44,38" {S}/>',
         definicion='Unir brazos, orejas y demás partes al cuerpo. Una buena costura hace que el muñeco se vea profesional.',
         pasos=['Ubica la pieza con alfileres antes de coser y mira cómo se ve.', 'Cose con la hebra larga que dejaste y la aguja lanera, pasando por un punto de cada pieza.', 'Remata y esconde la hebra dentro del cuerpo.'],
         tip='Cose siempre con el mismo color de la pieza que estás uniendo: así la costura desaparece.'),

    # ---------- Partes del tejido y patrones ----------
    dict(id='lazada', cat='tejido', nombre='Lazada', abrev='laz', en='yarn over (yo) en EE. UU. / yarn round hook (yrh) en Reino Unido',
         simbolo=f'<path d="M14,48 L42,14" {S}/><path d="M42,14 C46,10 49,14 45,17" {S}/><path d="M18,24 C30,20 40,30 32,40" {L}/>',
         definicion='Pasar el hilo por encima de la aguja, de atrás hacia adelante, para atraparlo con el ganchito. Es el movimiento que se repite en todos los puntos.'),
    dict(id='hebra-delantera', cat='tejido', nombre='Hebra delantera', abrev='hd', en='front loop only (FLO)',
         simbolo=f'<path d="M8,30 A22,12 0 0,1 52,30" {G}/><path d="M8,30 A22,12 0 0,0 52,30" {S}/>',
         definicion='Arriba de cada punto hay dos hebras que forman una V: la hebra delantera es la que queda más cerca de ti. Tejer solo en ella deja una rayita en el tejido y sirve para, por ejemplo, poner un borde de vestido o una falda en un amigurumi.'),
    dict(id='hebra-trasera', cat='tejido', nombre='Hebra trasera', abrev='ht', en='back loop only (BLO)',
         simbolo=f'<path d="M8,30 A22,12 0 0,1 52,30" {S}/><path d="M8,30 A22,12 0 0,0 52,30" {G}/>',
         definicion='La hebra de la V que queda más lejos de ti. Tejer solo en ella hace un borde marcado y es la forma de hacer la base plana de un zapato o de una canasta en amigurumi.',
         tip='Cuando tejas solo en una hebra, la otra queda libre. ¡No la ignores! Muchos patrones luego te piden tejer en esas hebras libres.'),
    dict(id='cadeneta-de-giro', cat='tejido', nombre='Cadeneta de giro', abrev='', en='turning chain',
         simbolo=f'<ellipse cx="18" cy="44" rx="5" ry="8" {S}/><ellipse cx="18" cy="28" rx="5" ry="8" {S}/><ellipse cx="18" cy="12" rx="5" ry="8" {S}/><path d="M40,12 V50 M32,12 H48 M35,34 L45,28" {S}/>',
         definicion='Las cadenetas que haces al empezar una fila o vuelta cerrada para llegar a la altura del punto que vas a tejer. Como guía: 1 cad para punto bajo, 2 para medio punto alto y 3 para punto alto.',
         tip='En punto alto la cadeneta de giro suele contar como el primer punto; en punto bajo no. Revisa siempre qué dice tu patrón.'),
    dict(id='vuelta-hilera', cat='tejido', nombre='Vuelta e hilera', abrev='v', en='round (rnd) / row',
         simbolo=f'<path d="M20,14 A10,10 0 1,0 30,24" {S}/><path d="M30,24 L27,19 M30,24 L25,26" {S}/><path d="M34,38 H52 M52,38 L48,35 M52,38 L48,41 M52,48 H34 M34,48 L38,45 M34,48 L38,51" {L}/>',
         definicion='La vuelta se teje en redondo, como en un amigurumi. La hilera se teje de ida y vuelta, girando el trabajo, como en una bufanda. En muchos patrones en español verás "vuelta" para las dos.'),
    dict(id='punto', cat='tejido', nombre='Punto', abrev='pto', en='stitch (st)',
         simbolo=x(20, 30, 7) + x(40, 30, 7),
         definicion='Cada puntada que tejes. Cuando el patrón dice "teje en el siguiente punto", se refiere a meter la aguja bajo las dos hebras de la V del punto de la vuelta anterior.'),
    dict(id='espacio', cat='tejido', nombre='Espacio', abrev='esp', en='space (sp)',
         simbolo=f'<ellipse cx="18" cy="32" rx="6" ry="4" transform="rotate(-50 18 32)" {S}/><ellipse cx="30" cy="24" rx="6" ry="4" {S}/><ellipse cx="42" cy="32" rx="6" ry="4" transform="rotate(50 42 32)" {S}/><path d="M10,46 H50" {G}/>',
         definicion='El huequito que forman una o varias cadenetas. Cuando el patrón dice "en el espacio", metes la aguja por debajo de las cadenetas, no dentro de ellas.'),
    dict(id='repetir', cat='tejido', nombre='Repetir', abrev='rep', en='repeat (rep)',
         simbolo='<text x="30" y="36" text-anchor="middle" font-family="Hanken Grotesk, sans-serif" font-size="30" font-weight="800" fill="#E74E96">* *</text><text x="30" y="52" text-anchor="middle" font-family="Hanken Grotesk, sans-serif" font-size="13" font-weight="800" fill="#9EA2F9">×6</text>',
         definicion='Los patrones ahorran espacio agrupando instrucciones. Lo que está entre asteriscos * * o entre paréntesis ( ) se repite las veces que diga el número.',
         pasos=['Lee el grupo: por ejemplo (2 pb, 1 aum).', 'Mira cuántas veces se repite: × 6.', 'Teje el grupo completo 6 veces seguidas.'],
         tip='El número entre corchetes al final de la vuelta, como [24], es el total de puntos que debes tener. Cuéntalos: es la mejor forma de pillar un error a tiempo.'),
    dict(id='muestra', cat='tejido', nombre='Muestra', abrev='', en='gauge / tension',
         simbolo=f'<rect x="14" y="14" width="32" height="32" rx="3" {S}/><path d="M14,24.7 H46 M14,35.3 H46 M24.7,14 V46 M35.3,14 V46" {G}/><path d="M14,52 H46 M14,49 V55 M46,49 V55" {L}/>',
         definicion='Un cuadrado de prueba tejido con la misma lana, aguja y punto de tu proyecto. Contando cuántos puntos y vueltas caben en 10 cm sabes si tu pieza saldrá del tamaño del patrón.',
         enlace=('recursos-rosina.html#calculadora', 'Calcular con tu muestra')),

    # ---------- Materiales ----------
    dict(id='aguja-crochet', cat='materiales', nombre='Aguja de crochet', abrev='', en='crochet hook', otros='También se llama ganchillo.', simbolo='<path d="M8,53 L43,14" stroke="#E74E96" stroke-width="6.5" stroke-linecap="round" fill="none"/><rect x="16" y="29.5" width="20" height="11" rx="5.5" transform="rotate(-48 26 35)" fill="#F28FC0" stroke="#E74E96" stroke-width="1.5"/><path d="M43,14 L48.5,8 C50.5,5.6 54.5,6.8 53.5,10.2" stroke="#E74E96" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" fill="none"/>',
         definicion='La aguja con ganchito en la punta. Su grosor se mide en milímetros: para amigurumi se usan agujas finas, de 2 a 3,5 mm, para que el tejido quede apretado.',
         enlace=('merceria.html#agujas-merceria', 'Ver agujas en la mercería')),
    dict(id='aguja-lanera', cat='materiales', nombre='Aguja lanera', abrev='', en='yarn needle / tapestry needle', icono='🪡',
         definicion='Una aguja grande de punta roma y ojo amplio. Sirve para coser las piezas, cerrar el final de los amigurumis y esconder las hebras.'),
    dict(id='marcador', cat='materiales', nombre='Marcador de puntos', abrev='MP', en='stitch marker (SM)', icono='📍',
         definicion='Un ganchito de plástico que se pone en un punto para no perderlo de vista, normalmente el primero de cada vuelta. Un clip o un hilo de otro color hacen el mismo trabajo.'),
    dict(id='ojos-seguridad', cat='materiales', nombre='Ojos de seguridad', abrev='', en='safety eyes', icono='👀',
         definicion='Ojitos plásticos con una arandela que se ajusta por dentro y no se sueltan. Se ponen antes de rellenar y cerrar la cabeza.',
         tip='Para bebés y niños menores de 3 años, mejor borda los ojos con hilo negro.',
         enlace=('merceria.html#herrajes-merceria', 'Ver ojos de seguridad')),
    dict(id='relleno', cat='materiales', nombre='Relleno', abrev='', en='stuffing / fiberfill', otros='También se llama guata o fibra siliconada.', icono='☁️',
         definicion='La fibra suave con la que se rellenan los amigurumis. Se pone de a poquitos, moldeando la pieza con los dedos.',
         tip='Rellena firme pero sin estirar el tejido: si ves el relleno entre los puntos, te pasaste o tu aguja es muy gruesa.',
         enlace=('merceria.html#relleno-merceria', 'Ver relleno en la mercería')),
    dict(id='grosor-hilo', cat='materiales', nombre='Grosor del hilo', abrev='', en='yarn weight', icono='🧶',
         definicion='Qué tan grueso es el hilo. La etiqueta suele indicar el grosor y la aguja recomendada. Para empezar amigurumis, un hilo de algodón de grosor medio con aguja de 2,5 a 3 mm es ideal.',
         enlace=('merceria.html#hilos-merceria', 'Ver hilos en la mercería')),
]
