CATEGORIAS = [
    ('tonos', 'Tonos de un mismo color'),
    ('fechas', 'Fechas especiales'),
    ('bebe', 'Para bebés'),
    ('amigurumi', 'Amigurumis'),
    ('hogar', 'Mantas y hogar'),
]

PALETAS = [
    # ---------- Tonos de un mismo color (del más claro al más oscuro) ----------
    dict(id='tonos-azules', cat='tonos', nombre='Azules',
         colores=[('Celeste', '#D6EAF8'), ('Azul cielo', '#A9CCE3'), ('Azul medio', '#5DADE2'), ('Azul rey', '#2E86C1'), ('Azul marino', '#1B4F72')],
         uso='Mantas en degradé, ropa de bebé, olas y peces.',
         tip='Un degradé queda precioso en mantas y bufandas: teje del tono más claro al más oscuro, o al revés.'),
    dict(id='tonos-rosas', cat='tonos', nombre='Rosas',
         colores=[('Rosa pálido', '#FDE2EC'), ('Rosa bebé', '#F9BCD3'), ('Rosa chicle', '#F28FC0'), ('Fucsia', '#E74E96'), ('Frambuesa', '#B8336A')],
         uso='Flores, corazones, mantas y detalles románticos.'),
    dict(id='tonos-verdes', cat='tonos', nombre='Verdes',
         colores=[('Menta', '#D5F0E3'), ('Verde agua', '#A3DCC4'), ('Verde hoja', '#6FBF8E'), ('Verde pino', '#2E7D52'), ('Verde bosque', '#1E4D35')],
         uso='Plantas, suculentas, hojas y cactus tejidos.',
         tip='Para una planta que se vea real, usa el verde más oscuro por dentro y los claros en las puntas de las hojas.'),
    dict(id='tonos-lilas', cat='tonos', nombre='Lilas y morados',
         colores=[('Lavanda', '#EDE4FA'), ('Lila', '#D2C1F2'), ('Violeta', '#A98BDB'), ('Morado', '#7552B3'), ('Uva', '#4A2F7A')],
         uso='Flores de lavanda, bolsos, unicornios y amigurumis de fantasía.'),
    dict(id='tonos-tierra', cat='tonos', nombre='Tierra y cafés',
         colores=[('Arena', '#F1E3D0'), ('Beige', '#DDC3A0'), ('Caramelo', '#B98555'), ('Café', '#7B4F2F'), ('Chocolate', '#4A2E1D')],
         uso='Ositos, perritos, gatitos y todo lo que tenga pelaje.'),
    dict(id='tonos-grises', cat='tonos', nombre='Grises y neutros',
         colores=[('Blanco hueso', '#F5F3EF'), ('Gris perla', '#D9D8DC'), ('Gris medio', '#A3A2A8'), ('Gris oscuro', '#66656B'), ('Carbón', '#333236')],
         uso='Elefantes, koalas, gatitos grises y decoración moderna.'),
    dict(id='tonos-sol', cat='tonos', nombre='Amarillos y naranjas',
         colores=[('Vainilla', '#FFF4CC'), ('Amarillo', '#FFE066'), ('Mostaza', '#E8B930'), ('Naranja', '#F29A38'), ('Naranja quemado', '#C8603F')],
         uso='Soles, girasoles, pollitos, zorros y mantas cálidas.'),

    # ---------- Fechas especiales ----------
    dict(id='amor-amistad', cat='fechas', nombre='Amor y amistad',
         colores=[('Rojo cereza', '#D72638'), ('Rosa chicle', '#F28FC0'), ('Blanco', '#FFFFFF'), ('Lila', '#C8A2E8')],
         uso='Corazones, llaveros y detalles para regalar en septiembre.',
         tip='Un corazón rojo con borde blanco se ve el doble de lindo en las fotos.'),
    dict(id='dia-madre', cat='fechas', nombre='Día de la madre',
         colores=[('Rosa Lana Rosa', '#E74E96'), ('Rosa suave', '#FBE4EF'), ('Verde hoja', '#7BAE7F'), ('Amarillo pollito', '#FFE08A')],
         uso='Flores tejidas, macetas y ramos que duran para siempre.'),
    dict(id='playa', cat='fechas', nombre='Vacaciones de playa',
         colores=[('Azul turquesa', '#2EC4B6'), ('Arena', '#F1DDBF'), ('Coral', '#FF7F6B'), ('Blanco', '#FFFFFF')],
         uso='Bolsos de playa, medusas, estrellas de mar y posavasos.'),

    # ---------- Bebés ----------
    dict(id='bebe-nina', cat='bebe', nombre='Baby shower niña',
         colores=[('Rosa bebé', '#F8C8DC'), ('Lila', '#D7C4F0'), ('Crema', '#FFF8E7'), ('Gris perla', '#D9D9DE')],
         uso='Mantas, sonajeros, zapatitos y móviles para cuna.'),
    dict(id='bebe-nino', cat='bebe', nombre='Baby shower niño',
         colores=[('Azul cielo', '#A7D3F5'), ('Verde agua', '#BFE8DF'), ('Crema', '#FFF8E7'), ('Gris perla', '#D9D9DE')],
         uso='Mantas, apegos, gorritos y animalitos de cuna.'),
    dict(id='bebe-neutro', cat='bebe', nombre='Bebé neutro',
         colores=[('Beige', '#E8D8C4'), ('Verde salvia', '#B7C9A8'), ('Mostaza suave', '#EBC96B'), ('Blanco hueso', '#FAF7F0')],
         uso='Perfecta cuando todavía no se sabe si es niña o niño.',
         tip='Para bebés usa hilo 100 % algodón: es suave, fresco y se lava fácil.'),

    # ---------- Amigurumis ----------
    dict(id='rosina', cat='amigurumi', nombre='Ovejita Rosina',
         colores=[('Café lana', '#A9786B'), ('Crema', '#FFF8F0'), ('Rosa vestido', '#F9C9E3'), ('Rosa moños', '#F5A8C0')],
         uso='¡Los colores de Rosina! Para tejer tu propia ovejita.',
         tip='Borda las mejillas con hilo rosa muy suave o píntalas con un poquito de rubor.'),
    dict(id='osito', cat='amigurumi', nombre='Osito clásico',
         colores=[('Café caramelo', '#B7794A'), ('Beige hocico', '#EAD2B5'), ('Negro', '#2B2B2B'), ('Rojo moño', '#D23C3C')],
         uso='El osito de toda la vida: cuerpo caramelo, hocico claro y un moño de color.'),
    dict(id='pollito', cat='amigurumi', nombre='Pollito de primavera',
         colores=[('Amarillo', '#FFD95A'), ('Naranja pico', '#F5A142'), ('Blanco', '#FFFFFF'), ('Verde hierba', '#8BC77A')],
         uso='Pollitos, patitos, flores y huevitos.'),
    dict(id='colombia', cat='amigurumi', nombre='Selección Colombia',
         colores=[('Amarillo', '#FCD116'), ('Azul', '#003893'), ('Rojo', '#CE1126')],
         uso='Balones, llaveros y muñequitos hinchas de la Selección.',
         tip='Como en la bandera: la mitad amarillo, un cuarto azul y un cuarto rojo.'),

    # ---------- Mantas y hogar ----------
    dict(id='pastel-sonador', cat='hogar', nombre='Pastel soñador',
         colores=[('Rosa palo', '#F4B6C2'), ('Verde menta', '#B8E0D2'), ('Crema', '#FFF6E5'), ('Dorado suave', '#E8C872')],
         uso='Una combinación tierna para coronas, flores, muñequitos y regalos para bebés.'),
    dict(id='cafe-colombiano', cat='hogar', nombre='Café colombiano',
         colores=[('Café oscuro', '#5C3A2E'), ('Canela', '#C08457'), ('Crema', '#F3E5D0'), ('Terracota', '#C8603F')],
         uso='Mantas, cojines, individuales y posavasos con aire de finca cafetera.'),
    dict(id='boho', cat='hogar', nombre='Boho',
         colores=[('Terracota', '#C8603F'), ('Mostaza', '#D9A13B'), ('Verde salvia', '#9CAF88'), ('Arena', '#E9D8C0')],
         uso='Bolsos, tapetes, cestos y colgantes de pared.'),
    dict(id='arcoiris-pastel', cat='hogar', nombre='Arcoíris pastel',
         colores=[('Rosa', '#F7B7C8'), ('Durazno', '#FDD0B1'), ('Amarillo', '#FFF1A8'), ('Menta', '#BFEBD6'), ('Celeste', '#BFDDF7'), ('Lila', '#D9C8F2')],
         uso='Mantas de rayas, cuadrados de la abuela (granny) y arcoíris decorativos.'),
    dict(id='atardecer', cat='hogar', nombre='Atardecer',
         colores=[('Coral', '#FF7F6B'), ('Durazno', '#FFB38A'), ('Rosa', '#F28FC0'), ('Morado', '#6A4C93')],
         uso='Bufandas en degradé, bolsos y mantas con cambio de color.',
         tip='Para un degradé, teje los colores en orden, del más claro al más oscuro.'),
]
